### ISSUE TITLE
Unsupported send() data function Writer()

### ISSUE THREAD

**Issue by mathiskeeper** [pwnall/node-xhr2#51]
Hello, Currently when building a POST request  im getting the below error when attempting to send the payload. After debugging i  see if fails during this check :

else if (data.buffer && data.buffer instanceof ArrayBuffer) {
        // ArrayBufferView
        body = Buffer.alloc(data.byteLength);
        offset = data.byteOffset;
        view = new Uint8Array(data.buffer);
        for (i = k = 0, ref1 = data.byteLength; (0 <= ref1 ? k < ref1 : k > ref1); i = 0 <= ref1 ? ++k : --k) {
          body[i] = view[i + offset];
        }
        this._body = body;

then the following exception occurs 

Unsupported send() data function Writer() {
        /**
         * Current length.
         * @type {number}
         */
        this.len = 0;
        /**
         * Operations head.
         * @type {Object}
         */
        this.head = new Op(noop, 0, 0);
        /**
         * Operations tail
         * @type {Object}
         */
        this.tail = this.head;
        /**
         * Linked forked states.
         * @type {Object|null}
         */
        this.states = null;

Any idea on what I would need to check or change ?

**Comment by geco** [comment]
I've the same problem, doing a simple Axios Post with an attached file, using package form-data.
Code is not changed from working version.
Unsupported send() data [object FormData]
    at XMLHttpRequestUpload._setData (node_modules/xhr2/lib/xhr2.js:1196:15)
    at XMLHttpRequest._sendHttp (node_modules/xhr2/lib/xhr2.js:458:21)
    at XMLHttpRequest.send (node_modules/xhr2/lib/xhr2.js:278:18)
    at dispatchXhrRequest (node_modules/axios/dist/node/axios.cjs:3160:13)


Can you help me please?
Thanks!
